# Create a New User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Michel",
  "mobile_number": "9768292392",
  "address": "12st Block Dallas Street"
}

###

# Get All Users
GET http://localhost:3000/users

###

# Create a New Post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Traveling to beach",
  "description": "spending a pleasent time with my family.",
  "user_id": 1,
  "images": ["image1.jpg", "image2.jpg"]
}

###

# Get All Posts
GET http://localhost:3000/posts

###

# Get Posts by User ID
GET http://localhost:3000/posts/1

###

# Update a Post
PUT http://localhost:3000/posts/1
Content-Type: application/json

{
  "title": "Hyderabad Dairies",
  "description": "Looking forward to writing new memories today's journey.",
  "images": ["updated_image1.jpg", "updated_image2.jpg"]
}

###

# Delete a Post
DELETE http://localhost:3000/posts/1
